# Generated by Django 5.2.7 on 2025-10-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Mới', 'Mới'), ('Đang xử lý', 'Đang xử lý'), ('Đang giao', 'Đang giao'), ('Hoàn thành', 'Hoàn thành'), ('Đã hủy', 'Đã hủy')], default='Mới', max_length=20),
        ),
    ]
