# Generated by Django 5.2.7 on 2025-10-23 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã giảm giá, ví dụ: GIAM10', max_length=50, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=0, help_text='Số tiền giảm (VND)', max_digits=10)),
                ('min_purchase_amount', models.DecimalField(decimal_places=0, default=0, help_text='Số tiền mua tối thiểu để áp dụng', max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Số tiền đã được giảm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, help_text='Tổng tiền ban đầu', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.voucher'),
        ),
    ]
