# Generated by Django 6.0 on 2026-01-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('qr', 'Chuyển khoản ngân hàng (QR)')], default='cod', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
