# Generated by Django 6.0 on 2026-01-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_payment_method_order_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, help_text='Ghi chú đơn hàng hoặc mã giao dịch', null=True),
        ),
    ]
