# Generated by Django 6.0 on 2026-01-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(editable=False, help_text='Mã đơn hàng hiển thị cho khách (VD: DH123456)', max_length=20, null=True, unique=True),
        ),
    ]
